## Ex 1. np.swapaxes(array, axis, axis) 2차원

In [47]:
import numpy as np

a=np.arange(3)
a=a.reshape(1,3)

In [48]:
y=np.swapaxes(a,0,1)

In [49]:
y.shape

(3, 1)

In [52]:
b=np.arange(6)
b=b.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
x=np.swapaxes(b,0,1)
x

array([[0, 3],
       [1, 4],
       [2, 5]])

## Ex 2. np.swapaxes(array, axis, axis) 3차원

axis = 0은 3차원 축,
axis = 1은 2차원 축,
axis = 2는 1차원 축,

In [73]:
c=np.arange(6).reshape(1,2,3)

In [74]:
c

array([[[0, 1, 2],
        [3, 4, 5]]])

In [75]:
c.shape

(1, 2, 3)

In [78]:
z=np.swapaxes(c,1,2) # 2차원 축과 1차원 축을 바꿔라
z.shape

(1, 3, 2)

In [79]:
z

array([[[0, 3],
        [1, 4],
        [2, 5]]])

In [80]:
n=np.swapaxes(z,0,2)
n.shape

(2, 3, 1)

## Ex 3. np.transpose()

transepose()는 사용자가 원하는대로 축을 한번에 여러개 바꿀 수 있다.

In [81]:
t=np.arange(6).reshape(2,3)

In [82]:
t

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
y=np.transpose(t)
y

array([[0, 3],
       [1, 4],
       [2, 5]])

In [86]:
g=t.T
g

array([[0, 3],
       [1, 4],
       [2, 5]])

## 차원 추가

In [87]:
x=np.arange(2)

In [88]:
x

array([0, 1])

In [89]:
x.shape

(2,)

In [97]:
# 첫 번째 축에 차원을 추가한다.
# expand_dims 대신에 x[np.newaxis,:] 또는 x[np.newaxis]도 사용 가능

y=np.expand_dims(x,axis=0)

In [98]:
y.shape

(1, 2)

튜플을 사용하여 2개의 축에 차원을 한꺼번에 추가할 수도 있다.

In [104]:
z=np.expand_dims(x,axis=(0,1))

In [105]:
z.shape

(1, 1, 2)